apiVersion: v1
kind: Pod
metadata:
  name: alpine-curl
  namespace: dev
  labels:
    name: alpine-curl
spec:
  serviceAccount: pod-inspector
  containers:
    - name: alpine-curl
      image: lmacademy/alpine-curl:1.0.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
