apiVersion: v1
kind: Service
metadata:
  name: kts-user-nodeport
spec:
  type: NodePort
  selector:
    app: kts-user-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
      protocol: TCP
