apiVersion: v1
kind: Pod
metadata:
  name: color-api-pod
  labels:
    name: color-api
spec:
  containers:
    - name: color-api
      image: kavinduorg/color-api:1.4.0
      env:
        - name: DEFAULT_COLOR
          valueFrom:
            configMapKeyRef:
              name: color-config
              key: COLOR
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
      ports:
        - containerPort: 80
