apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-demo-pod
  labels:
    app: empty-dir-demo-pod
spec:
  containers:
    - name: empty-dir-demo-writer
      image: busybox
      command:
        - "sh"
        - "-c"
        - "sleep 3600"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: temp-storage
          mountPath: /usr/share/temp
    - name: empty-dir-demo-reader
      image: busybox
      command:
        - "sh"
        - "-c"
        - "sleep 3600"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: temp-storage
          mountPath: /temp
          readOnly: true
  volumes:
    - name: temp-storage
      emptyDir: {}
