apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api
  labels:
    app: color-api
spec:
  selector:
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
        - name: color-api
          image: kavinduorg/color-api:6.0.0
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-colordb-creds
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-colordb-creds
                  key: password
            - name: DB_URL
              value: "mongodb://$(DB_USERNAME):$(DB_PASSWORD)@mongodb-ss-0.mongodb-svc.default.svc.cluster.local:27017/colordb"
          ports:
            - containerPort: 80
