apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api-depl
spec:
  replicas: 5
  selector:
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
        - name: color-api
          image: kavinduorg/color-api:1.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DELAY_STARTUP
              value: "false"
            - name: FAIL_LIVENESS
              value: "false"
            - name: FAIL_READINESS
              value: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /up
              port: 80
            failureThreshold: 100
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            failureThreshold: 3
            periodSeconds: 5
