apiVersion: v1
kind: Pod
metadata:
  name: nginx-restricted
  labels:
    app: nginx-restricted
spec:
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:1.27
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
