apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
  labels:
    app: secret-demo
spec:
  containers:
    - name: secret-demo
      image: busybox
      command:
        - "sh"
        - "-c"
        - "echo ${DB_USER} - ${DB_PASS} &&  sleep 1800"
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db-user

        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: db-pass
