apiVersion: v1
kind: Pod
metadata:
  name: traffic-gen
  labels:
    app: traffic-gen
spec:
  containers:
    - name: traffic-gen
      image: kavinduorg/traffic-gen:1.1.0
      args:
        - "color-api-nodeport/api"
        - "2"
