apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
  labels:
    app: secret-demo
spec:
  containers:
    - name: secret-demo
      image: busybox
      command:
        - "sh"
        - "-c"
        - "sleep 1000"
      volumeMounts:
        - mountPath: /etc/db
          name: db-secrets

  volumes:
    - name: db-secrets
      secret:
        secretName: db-creds
