apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app
spec:
  selector:
    matchLabels:
      app: color-app
  template:
    metadata:
      labels:
        app: color-app
    spec:
      containers:
        - name: color-app
          image: lmacademy/color-api:2.0.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-colordb-creds
                  key: USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-colordb-creds
                  key: PASSWORD
            - name: DB_URL
              value: "mongodb://$(DB_USER):$(DB_PASSWORD)@mongodb-ss-0.mongodb-svc:27017/colordb"
          ports:
            - containerPort: 80
