apiVersion: v1
kind: Pod
metadata:
  name: color-api-backend-pod
  labels:
    app: color-api
    environment: local
    tier: backend
spec:
  containers:
    - name: color-api
      image: kavinduorg/color-api:1.0.0
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: color-api-frontend-pod
  labels:
    app: color-api
    environment: local
    tier: frontend
spec:
  containers:
    - name: color-nginx
      image: nginx:1.27.0
      ports:
        - containerPort: 80
