apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-vol
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/local1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-vol-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage

---
apiVersion: v1
kind: Pod
metadata:
  name: local-volume-pod1
  labels:
    app: local-volume-pod
spec:
  containers:
    - name: local-volume
      image: busybox
      command:
        - "sh"
        - "-c"
        - "sleep 3600"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: local-volume
          mountPath: /mnt/local
  volumes:
    - name: local-volume
      persistentVolumeClaim:
        claimName: local-vol-claim

---
apiVersion: v1
kind: Pod
metadata:
  name: local-volume-pod2
  labels:
    app: local-volume-pod2
spec:
  containers:
    - name: local-volume
      image: busybox
      command:
        - "sh"
        - "-c"
        - "sleep 3600"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: local-volume
          mountPath: /mnt/local
  volumes:
    - name: local-volume
      persistentVolumeClaim:
        claimName: local-vol-claim
