apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-ss
spec:
  serviceName: busybox
  replicas: 2
  selector:
    matchLabels:
      app: busyBox
  template:
    metadata:
      labels:
        app: busyBox
    spec:
      containers:
        - name: busybox-container
          image: busybox
          command:
            - "sh"
            - "-c"
            - "sleep 3600"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: local-volume
              mountPath: /mnt/local
  volumeClaimTemplates:
    - metadata:
        name: local-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 128Mi
